### ISSUE TITLE
Installation of Partner first name, last name on Odoo 8.0 is not working

### ISSUE THREAD

**Issue by baumgaro** [OCA/partner-contact#3]
File "/.../oca_addons/partner_contact/partner_firstname/partner.py", line 20, in <module>
    from openerp.osv.orm import Model, fields
ImportError: cannot import name fields

**Comment by bwrsandman** [comment]
None of these modules have been ported to 8.0 yet.

**Comment by pedrobaeza** [comment]
But he is right, correct line would be:

from openerp.osv import orm, fields

and then:

class ...(orm.Model)

**Comment by bwrsandman** [comment]
Indeed. But for some reason it still works on 7.0. I have no idea why and I use it.

**Comment by bwrsandman** [comment]
@baumgaro The bug you're describing is fixed in #5 with 5166eda, however, partner_firstname, still fails and has been set to unported c4f88dbf7afa32c709f5d6944bdebac136125cd0

An issue on porting partner_firstname has been opened in #11

**Comment by willArrive** [comment]
Very useful the answer of pedrobaeza 
Tks very much
